baseURL: "http://martimfasantos.github.io"
languageCode: "en-us"
title: "Martim's Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# additional pages that are added to the navbar
Menus:
  main:
    - identifier: blog
      name: Blog
      title: My Blog
      url: /blog
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # ...


params:
  title: "martim."
  # description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

    darkmode:
      textColor: "#e4e6eb"
      secondaryTextColor: "#b0b3b8"
      textLinkColor: "#ffffff"
      textSecondaryLinkColor: "#bbbbbb"
      backgroundColor: "#18191a"
      secondaryBackgroundColor: "#212529"
      primaryColor: "#ffffff"
      secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    # brandName: "martim"
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : false
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Martim."
    subtitle: "A ML and GenAI enthusiast."
    location: "Lisbon, Portugal"
    content: "A passionate machine learning engineer and data scientist. I tend to leverage cutting-edge algorithms and data-driven solutions to build models that are insightful, efficient, and deliver results."
    image: "/me/hero-round.png"
    bottomImage:
      enable: true
    roundImage: true
    button:
      enable: true
      name: "Resume"
      url: "/cv/cv-martim-santos-en.pdf"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/martimfasantos/
        - icon: fab fa-github
          url: https://github.com/martimfasantos
        - icon: fab fa-instagram
          url: https://www.instagram.com/martimfasantos/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/me/about.jpg"
    content: |-
      I am a __MSc graduate__ from Instituto Superior Técnico (IST) in Portugal. During my studies, I had the opportunity to participate 
      in an Erasmus exchange program at Technische Universität München (TUM) in Munich. My academic journey has been centered on 
      Computer Science with specializations in Artificial Intelligence and Data Science.

      Recently, __I successfully defended my MSc Thesis__, _Aligning Language Models with Human Feedback 
      without Reinforcement Learning_. The research delves into Generative AI, Deep Learning, and NLP, and was conducted under the supervision 
      of [André F. T. Martins](https://andre-martins.github.io/), Head of Research at Unbabel, and [Sweta Agrawal](https://sweta20.github.io/), 
      a postdoctoral researcher at Instituto de Telecomunicações, in collaboration with [Unbabel](https://unbabel.com/) and [SARDINE Lab](https://sardine-lab.github.io/).

      I hold a particular interest in the fields of __Machine Learning__, __Data Science__, and __GenAI__.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "pandas"
        - "TensorFlow"
        - "Docker"
        - "SQL"
        - "FastAPI"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Data Scientist"
        company: "DareData"
        companyUrl: "https://www.daredata.ai/"
        companyLogo: "/logos/daredata-logo-white.png"
        date: "Jan 2025 - present"
        info:
          enable: false
        featuredLink:
          enable: false
          name: ""
          url: ""
        content: |-
          I am currently working as a GenAI Engineer on a project with NOS Portugal to integrate Generative AI, 
          aiming to enhance service quality and streamline processes to reduce costs.

      - job: "Software Developer"
        company: "Sky Portugal"
        companyUrl: "https://www.sky.com/"
        companyLogo: "/logos/sky-logo.png"
        date: "Jul 2024 - Aug 2024"
        info: 
          enable: true
          content: "Summer Intership as an Apprentice Backend Developer"
        featuredLink:
          enable: false
          name: ""
          url: ""
        content: |-
          Developed, enhanced and deployed a Slack bot to automate manual processes, migrating its codebase from Python to Kotlin 
          for improved structure and test coverage. This provided a more scalable foundation for future development and integrations."

      

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "MSc Degree in Computer Science and Engineering"
        school:
          name: "Instituto Superior Técnico"
          url: "https://tecnico.ulisboa.pt/"
        date: "2022 - 2024"
        GPA: "18 out of 20"
        content: |-
          My specializations were in Artificial Intelligence :robot: and Data Science :bar_chart:. 
          
          :scroll: For my MSc thesis, I worked on Generative AI, Deep Learning, and NLP, focusing on the alignment of Language Models
          with human feedback without reinforcement learning, for machine translation and summarization.

          :point_right_tone1: Check out my blog post on [My MSc Thesis](/blog/thesis/) to learn more.
        erasmus:
          enable: true
          school: "Technische Universität München"
          url: "https://www.tum.de/"
          content: |-
            :earth_africa: I participated in an Erasmus exchange program, where I successfully completed courses in:
            - Natural Language Processing
            - Business Analytics and Machine Learning
            - Query Optimization

            :point_right_tone1: Check out my blog post on [My Erasmus Experience](/blog/erasmus/) to learn more.
        featuredLink:
          enable: true
          name: "My academic record :graduation_cap:"
          url: "/courses"
      
      - title: "BSc Degree in Computer Science and Engineering"
        school:
          name: "Instituto Superior Técnico"
          url: "https://tecnico.ulisboa.pt/"
        date: "2019 - 2022"
        GPA: "17.43 out of 20"
        content: |-

        featuredLink:
          enable: true
          name: "My academic record :graduation_cap:"
          url: "/courses"

      - title: "Elementary & High School"
        school:
          name: "Colégio de São Tomás"
          url: "https://colegiodestomas.com/"
        date: "2004 - 2019"
        GPA: "18.95 out of 20"
        featuredLink:
          enable: false


  # projects
  projects:
    enable: true
    items:
      - title: Diabetes Risk Predictor
        description: End-to-end machine learning pipeline that leverages health and demographic data to predict diabetes risk with high accuracy.
        image: /projects/diabetes-risk-predictor.png # image ratio: 7:5
        # featured:
        #   name: Demo
        #   link: 
        badges:
          - "Python"
          - "Jupyter Notebook"
          - "ML"
          - "EDA"
          - "scikit-learn"
          - "Optuna"
        links:
          - icon: fab fa-github
            url: https://github.com/martimfasantos/Diabetes-Risk-Predictor
        
      - title: CustomPOs for SLMs
        description: Novel Preference Optimization Algorithms for state-of-the-art small LMs, enhancing performance in GenAI and NLP tasks.
        image: /projects/custompos-for-slms.png # image ratio: 7:5
        # featured:
        #   name: Demo
        #   link: 
        badges:
          - "Python"
          - "HuggingFace"
          - "NLP"
          - "transformers"
          - "PyTorch"
          - "LLMs"
        links:
          - icon: fab fa-github
            url: https://github.com/martimfasantos/CustomPOs-for-SLMs
            
      - title: LLMeals - Analytics Cup
        description: EDA & Predictive model developed for LLMeals - predicts whether a customer will like or dislike a suggested recipe based on their preferences and dietary requirements.
        image: /projects/analytics-cup.png # image ratio: 7:5
        # featured:
        #   name: Demo
        #   link: 
        badges:
          - "Python"
          - "Jupyter Notebook"
          - "ML"
          - "EDA"
          - "scikit-learn"
          - "Matplotlib"
        links:
          - icon: fab fa-github
            url: https://github.com/martimfasantos/AnalyticsCup24

    allProjects:
      enable: true
      title: "All my projects :man_technologist:"
      link: "/all-projects"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com


  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you as soon as possible!
    # btnName: Mail me
    # btnLink: mailto:martimfasantos@gmail.com
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: mgvooejk # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"
      messageRows: 5
    btnName: "Send"

  footer:
    recentPosts:
      enable: true
      path: "blog"
      count: 3
      title: Recent Posts
      disableFeaturedImage: false
    socialNetworks:
      linkedin: https://www.linkedin.com/in/martimfasantos/
      github: https://github.com/martimfasantos
      # twitter: https://twitter.com
      instagram: https://www.instagram.com/martimfasantos/
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
